CONFIG_ZMK_BEHAVIORS_QUEUE_SIZE=512

# Force the nRF52840 to use its internal 32kHz RC oscillator
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y

# Configure calibration intervals to maintain USB timing stability
CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=n
CONFIG_CLOCK_CONTROL_NRF_CALIBRATION_LF_ALWAYS_ON=y
